### ISSUE TITLE
Feature request: Add support for receptive field

### ISSUE THREAD

**Issue by kHarshit** [frgfm/torch-scan#12]
Hi, 

Thanks for your library. It works great with torchvision models.

Is it possible to add support for the receptive field e.g. in https://github.com/sksq96/pytorch-summary/pull/47.

**Comment by frgfm** [comment]
Hi @kHarshit,

Very sorry for the late reply, for unknown reasons I did not get a notification about your issue!
Glad it's helping, and thanks for the reference. I already intended to work on this, I'll look into this shortly!

**Comment by frgfm** [comment]
Hello there @kHarshit,

Finally made a proper PR to address your request in #21 ! Let me know what you think, I will probably merge it even though it only supports highway nets. For models with multiple branches or residual connections, I'll have to find another way later. I took a different approach than the one you referred to, but it looks like it's working well!

**Comment by frgfm** [comment]
Closing this as it's addressed by #21. For support of all type of architecture, I'll have to change the crawling method and probably use onnx conversion. I'll look into this later!

@kHarshit feel free to reopen if you encounter any issue or think this was not tackled!
